version: '3'

services:
  recipe_api:
    container_name: recipe_api
    command: npm start
    restart: always
    environment:
      - NODE_ENV=dev
      - PORT=80
    build:
      context: .
    depends_on:
      - redis
    ports:
      - "80:80"
    networks:
      - app-connect

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-connect

networks:
  app-connect:
    driver: bridge